#!/usr/bin/env python3
"""Export the Mogwarts game sounds for Roblox.

    pip install numpy scipy soundfile
    python3 sfx/roblox_export.py

Roblox limits how many audio files you may upload, so the one-shot sounds are packed into a few
long "sheet" files with half a second of silence between them. Each loop gets its own file.
Writes:
    roblox/audio/*.ogg            the files to upload (8 in total)
    roblox/MogwartsSounds.lua     a ModuleScript that knows where every sound and variant sits
                                  in which file; after uploading you only fill in ASSET_IDS
"""

import json
import sys
from pathlib import Path

import numpy as np
import soundfile as sf

sys.path.insert(0, str(Path(__file__).resolve().parent))
import synth  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "roblox"
GAP = 0.5

# which manifest categories end up in which sheet file
SHEETS = {
    "combat": ["game_combat", "game_affinity"],
    "interface": ["game_ui", "game_rewards"],
    "world": ["game_world"],
}

# playback defaults per sound: Roblox volume, random pitch spread (+/-), hearing range in studs
DEFAULTS = {"volume": 0.4, "pitch": 0.0, "range": 90}
TUNING = {
    "cast": (0.35, 0.06, 90), "impact": (0.4, 0.06, 90), "blast": (0.5, 0.04, 120), "blast_whoosh": (0.3, 0.05, 100),
    "charge_loop": (0.3, 0, 60), "charge_full": (0.4, 0.02, 70), "charge_release": (0.5, 0.04, 110),
    "shield_up": (0.4, 0.03, 80), "shield_block": (0.45, 0.06, 90), "dash": (0.35, 0.06, 70),
    "mythic_cast": (0.45, 0.02, 140), "duel_draw": (0.3, 0.04, 50), "duel_holster": (0.25, 0.04, 50),
    "knockout": (0.5, 0.02, 120), "defeat": (0.5, 0, 120), "respawn": (0.4, 0, 80),
    "burn_tick": (0.3, 0.08, 60), "frost_slow": (0.35, 0.05, 70), "lifesteal": (0.35, 0.05, 70),
    "crystal_shatter": (0.4, 0.05, 90),
    "reroll": (0.4, 0.05, 0), "reveal_common": (0.35, 0, 0), "reveal_rare": (0.45, 0, 0), "reveal_epic": (0.5, 0, 0),
    "reveal_legendary": (0.55, 0, 0), "reveal_mythic": (0.6, 0, 0), "code_redeem": (0.45, 0, 0),
    "ui_click": (0.35, 0.03, 0), "ui_hover": (0.15, 0.03, 0), "ui_open": (0.35, 0.02, 0), "ui_close": (0.3, 0.02, 0),
    "ui_tab": (0.3, 0.04, 0), "ui_denied": (0.35, 0, 0),
    "magic_door_open": (0.5, 0.04, 60), "magic_door_close": (0.5, 0.04, 60), "clock_bell": (0.6, 0, 500),
    "moonpool_loop": (0.4, 0, 80), "underwater_loop": (0.4, 0, 80), "deadwood_loop": (0.45, 0, 150),
    "shore_loop": (0.45, 0, 150),
}
AFFINITY = {
    "Ember": "aff_fire", "Solar": "aff_fire", "Frost": "aff_ice", "Crystal": "aff_ice", "Gale": "aff_wind",
    "Storm": "aff_storm", "Verdant": "aff_nature", "Shadow": "aff_dark", "Bloodmoon": "aff_dark", "Void": "aff_dark",
    "Radiant": "aff_light", "Celestial": "aff_light", "Eclipse": "aff_light",
}

def write_ogg(path, x):
    """OGG Vorbis, written in small blocks (libsndfile can crash on one big write)."""
    with sf.SoundFile(path, "w", synth.SR, 1, format="OGG", subtype="VORBIS") as f:
        for i in range(0, len(x), 4096):
            f.write(x[i:i + 4096])


MODULE_HEAD = '''-- MogwartsSounds: every effect of the Mogwarts sound pack in one place.
-- Generated by sfx/roblox_export.py. After uploading the files in roblox/audio/, only fill in ASSET_IDS.
--
--   local Sounds = require(game.ReplicatedStorage.WizardShared.MogwartsSounds)
--   Sounds.play("cast", part)                  -- 3D: on a part or attachment
--   Sounds.play("impact", somePosition)        -- 3D: at a Vector3 in the world
--   Sounds.play("ui_click")                    -- 2D: no position (interface sounds)
--   Sounds.affinity(aff.Name, part)            -- the affinity flavour layer (fire, ice, dark...)
--   local s = Sounds.loop("charge_loop", part) -- looping; s:Destroy() stops it
--
-- Every call picks a random variant and nudges the pitch a little, so repeats never sound identical.
-- A sound whose file is not uploaded yet returns nil (and stays silent), so callers can fall back.
local SoundService = game:GetService("SoundService")
local Debris = game:GetService("Debris")
local ContentProvider = game:GetService("ContentProvider")

local Sounds = {}

-- Paste the asset id of each uploaded file here (the number from rbxassetid://123456789).
Sounds.ASSET_IDS = {
'''

MODULE_TAIL = '''
local function hostFor(where)
	if typeof(where) == "Vector3" then
		local a = Instance.new("Attachment")
		a.WorldPosition = where
		a.Parent = workspace.Terrain
		Debris:AddItem(a, 8)
		return a
	end
	return where or SoundService
end

local function make(def, where, opts)
	local id = Sounds.ASSET_IDS[def.file]
	if not id or id == 0 then return nil end
	local s = Instance.new("Sound")
	s.Name = "MW_" .. def.file
	s.SoundId = "rbxassetid://" .. tostring(id)
	s.Volume = def.volume * (opts.volume or 1)
	s.PlaybackSpeed = (opts.pitch or 1) * (1 + (math.random() * 2 - 1) * (def.pitch or 0))
	s.RollOffMode = Enum.RollOffMode.InverseTapered
	s.RollOffMinDistance = 8
	s.RollOffMaxDistance = def.range > 0 and def.range or 90
	if opts.group then s.SoundGroup = opts.group end
	s.Parent = hostFor(where)
	return s
end

-- One-shot. `where` is a part/attachment, a Vector3, or nil for 2D. opts: volume, pitch (multipliers), group.
function Sounds.play(name, where, opts)
	local def = Sounds.LIST[name]
	if not def or not def.parts then return nil end
	opts = opts or {}
	local s = make(def, where, opts)
	if not s then return nil end
	local part = def.parts[math.random(#def.parts)]
	local start, len = part[1], part[2]
	-- play only this sound's stretch of the sheet
	local precise = pcall(function()
		s.PlaybackRegionsEnabled = true
		s.PlaybackRegion = NumberRange.new(start, start + len)
	end)
	s.TimePosition = start
	s:Play()
	local life = len / s.PlaybackSpeed
	if not precise then
		task.delay(life, function() if s.Parent then s:Stop() end end)
	end
	Debris:AddItem(s, life + 1)
	return s
end

-- Looping sound (charge hum, zone ambience). Returns the Sound so the caller can fade or stop it.
function Sounds.loop(name, where, opts)
	local def = Sounds.LIST[name]
	if not def or not def.loop then return nil end
	local s = make(def, where, opts or {})
	if not s then return nil end
	s.Looped = true
	s:Play()
	return s
end

-- The flavour layer for an affinity, played on top of the cast.
function Sounds.affinity(affinityName, where, opts)
	local key = Sounds.AFFINITY[affinityName or ""]
	return key and Sounds.play(key, where, opts) or nil
end

-- Call once on each client so the files are loaded before the first spell.
function Sounds.preload()
	local list = {}
	for _, id in pairs(Sounds.ASSET_IDS) do
		if id ~= 0 then
			local s = Instance.new("Sound")
			s.SoundId = "rbxassetid://" .. tostring(id)
			table.insert(list, s)
		end
	end
	if #list > 0 then
		task.spawn(function() pcall(ContentProvider.PreloadAsync, ContentProvider, list) end)
	end
end

return Sounds
'''


def main():
    manifest = json.loads(synth.MANIFEST.read_text(encoding="utf-8"))
    by_cat = {c["id"]: c["sounds"] for c in manifest["categories"]}
    (OUT / "audio").mkdir(parents=True, exist_ok=True)

    files, entries = [], []
    for sheet, cats in SHEETS.items():
        chunks, pos = [], 0.0
        for cat in cats:
            for sound in by_cat[cat]:
                if sound.get("loop"):
                    continue
                parts = []
                for variant in range(1, sound.get("variants", 1) + 1):
                    x = synth.render(sound["id"], sound["duration"], variant)
                    chunks += [x, np.zeros(synth.n(GAP))]
                    parts.append((pos, len(x) / synth.SR))
                    pos += (len(x) + synth.n(GAP)) / synth.SR
                entries.append((sound["id"], sheet, parts))
        data = np.concatenate(chunks).astype(np.float32)
        name = f"sheet_{sheet}.ogg"
        write_ogg(OUT / "audio" / name, data)
        files.append((sheet, name, len(data) / synth.SR))

    for cat in SHEETS["combat"] + SHEETS["interface"] + SHEETS["world"]:
        for sound in by_cat[cat]:
            if sound.get("loop"):
                x = synth.render(sound["id"]).astype(np.float32)
                name = f"loop_{sound['id']}.ogg"
                write_ogg(OUT / "audio" / name, x)
                files.append((sound["id"], name, len(x) / synth.SR))
                entries.append((sound["id"], sound["id"], None))

    lua = [MODULE_HEAD]
    width = max(len(key) for key, _, _ in files)
    for key, name, secs in files:
        lua.append(f"\t{key} = 0,{' ' * (width - len(key))} -- {name} ({secs:.1f} s)\n")
    lua.append("}\n\n-- Affinity -> flavour layer\nSounds.AFFINITY = {\n")
    for aff, key in AFFINITY.items():
        lua.append(f'\t{aff} = "{key}",\n')
    lua.append("}\n\n-- file, volume, pitch spread, range (studs; 0 = 2D), and per variant {start, length} in seconds\n")
    lua.append("Sounds.LIST = {\n")
    for sid, file, parts in entries:
        vol, pitch, rng = TUNING.get(sid, (DEFAULTS["volume"], DEFAULTS["pitch"], DEFAULTS["range"]))
        head = f'\t{sid} = {{ file = "{file}", volume = {vol}, pitch = {pitch}, range = {rng}, '
        if parts is None:
            lua.append(head + "loop = true },\n")
        else:
            spans = ", ".join(f"{{ {a:.3f}, {b:.3f} }}" for a, b in parts)
            lua.append(head + f"parts = {{ {spans} }} }},\n")
    lua.append("}\n")
    lua.append(MODULE_TAIL)
    (OUT / "MogwartsSounds.lua").write_text("".join(lua), encoding="utf-8")

    for key, name, secs in files:
        size = (OUT / "audio" / name).stat().st_size // 1024
        print(f"{name:32} {secs:6.1f} s  {size:5d} KB")
    print(f"{len(entries)} sounds in {len(files)} files -> {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
