-- MogwartsSounds: every effect of the Mogwarts sound pack in one place.
-- Generated by sfx/roblox_export.py. After uploading the files in roblox/audio/, only fill in ASSET_IDS.
--
--   local Sounds = require(game.ReplicatedStorage.WizardShared.MogwartsSounds)
--   Sounds.play("cast", part)                  -- 3D: on a part or attachment
--   Sounds.play("impact", somePosition)        -- 3D: at a Vector3 in the world
--   Sounds.play("ui_click")                    -- 2D: no position (interface sounds)
--   Sounds.affinity(aff.Name, part)            -- the affinity flavour layer (fire, ice, dark...)
--   local s = Sounds.loop("charge_loop", part) -- looping; s:Destroy() stops it
--
-- Every call picks a random variant and nudges the pitch a little, so repeats never sound identical.
-- A sound whose file is not uploaded yet returns nil (and stays silent), so callers can fall back.
local SoundService = game:GetService("SoundService")
local Debris = game:GetService("Debris")
local ContentProvider = game:GetService("ContentProvider")

local Sounds = {}

-- Paste the asset id of each uploaded file here (the number from rbxassetid://123456789).
Sounds.ASSET_IDS = {
	combat = 0,          -- sheet_combat.ogg (68.2 s)
	interface = 0,       -- sheet_interface.ogg (25.9 s)
	world = 0,           -- sheet_world.ogg (8.6 s)
	charge_loop = 0,     -- loop_charge_loop.ogg (2.0 s)
	moonpool_loop = 0,   -- loop_moonpool_loop.ogg (8.0 s)
	underwater_loop = 0, -- loop_underwater_loop.ogg (6.0 s)
	deadwood_loop = 0,   -- loop_deadwood_loop.ogg (8.0 s)
	shore_loop = 0,      -- loop_shore_loop.ogg (8.0 s)
}

-- Affinity -> flavour layer
Sounds.AFFINITY = {
	Ember = "aff_fire",
	Solar = "aff_fire",
	Frost = "aff_ice",
	Crystal = "aff_ice",
	Gale = "aff_wind",
	Storm = "aff_storm",
	Verdant = "aff_nature",
	Shadow = "aff_dark",
	Bloodmoon = "aff_dark",
	Void = "aff_dark",
	Radiant = "aff_light",
	Celestial = "aff_light",
	Eclipse = "aff_light",
}

-- file, volume, pitch spread, range (studs; 0 = 2D), and per variant {start, length} in seconds
Sounds.LIST = {
	cast = { file = "combat", volume = 0.35, pitch = 0.06, range = 90, parts = { { 0.000, 0.600 }, { 1.100, 0.600 }, { 2.200, 0.600 }, { 3.300, 0.600 } } },
	impact = { file = "combat", volume = 0.4, pitch = 0.06, range = 90, parts = { { 4.400, 0.900 }, { 5.800, 0.900 }, { 7.200, 0.900 }, { 8.600, 0.900 } } },
	blast = { file = "combat", volume = 0.5, pitch = 0.04, range = 120, parts = { { 10.000, 2.000 }, { 12.500, 2.000 }, { 15.000, 2.000 } } },
	blast_whoosh = { file = "combat", volume = 0.3, pitch = 0.05, range = 100, parts = { { 17.500, 1.000 }, { 19.000, 1.000 } } },
	charge_full = { file = "combat", volume = 0.4, pitch = 0.02, range = 70, parts = { { 20.500, 0.800 } } },
	charge_release = { file = "combat", volume = 0.5, pitch = 0.04, range = 110, parts = { { 21.800, 1.200 }, { 23.500, 1.200 } } },
	shield_up = { file = "combat", volume = 0.4, pitch = 0.03, range = 80, parts = { { 25.200, 1.500 }, { 27.200, 1.500 } } },
	shield_block = { file = "combat", volume = 0.45, pitch = 0.06, range = 90, parts = { { 29.200, 0.800 }, { 30.500, 0.800 }, { 31.800, 0.800 } } },
	dash = { file = "combat", volume = 0.35, pitch = 0.06, range = 70, parts = { { 33.100, 0.600 }, { 34.200, 0.600 }, { 35.300, 0.600 } } },
	mythic_cast = { file = "combat", volume = 0.45, pitch = 0.02, range = 140, parts = { { 36.400, 1.600 }, { 38.500, 1.600 } } },
	duel_draw = { file = "combat", volume = 0.3, pitch = 0.04, range = 50, parts = { { 40.600, 0.600 }, { 41.700, 0.600 } } },
	duel_holster = { file = "combat", volume = 0.25, pitch = 0.04, range = 50, parts = { { 42.800, 0.500 }, { 43.800, 0.500 } } },
	knockout = { file = "combat", volume = 0.5, pitch = 0.02, range = 120, parts = { { 44.800, 1.500 } } },
	defeat = { file = "combat", volume = 0.5, pitch = 0, range = 120, parts = { { 46.800, 2.500 } } },
	respawn = { file = "combat", volume = 0.4, pitch = 0, range = 80, parts = { { 49.800, 2.000 } } },
	burn_tick = { file = "combat", volume = 0.3, pitch = 0.08, range = 60, parts = { { 52.300, 0.400 }, { 53.200, 0.400 }, { 54.100, 0.400 } } },
	frost_slow = { file = "combat", volume = 0.35, pitch = 0.05, range = 70, parts = { { 55.000, 0.800 } } },
	lifesteal = { file = "combat", volume = 0.35, pitch = 0.05, range = 70, parts = { { 56.300, 0.800 } } },
	crystal_shatter = { file = "combat", volume = 0.4, pitch = 0.05, range = 90, parts = { { 57.600, 1.000 } } },
	aff_fire = { file = "combat", volume = 0.4, pitch = 0.0, range = 90, parts = { { 59.100, 0.800 } } },
	aff_ice = { file = "combat", volume = 0.4, pitch = 0.0, range = 90, parts = { { 60.400, 0.800 } } },
	aff_wind = { file = "combat", volume = 0.4, pitch = 0.0, range = 90, parts = { { 61.700, 0.800 } } },
	aff_storm = { file = "combat", volume = 0.4, pitch = 0.0, range = 90, parts = { { 63.000, 0.800 } } },
	aff_nature = { file = "combat", volume = 0.4, pitch = 0.0, range = 90, parts = { { 64.300, 0.800 } } },
	aff_dark = { file = "combat", volume = 0.4, pitch = 0.0, range = 90, parts = { { 65.600, 0.800 } } },
	aff_light = { file = "combat", volume = 0.4, pitch = 0.0, range = 90, parts = { { 66.900, 0.800 } } },
	ui_click = { file = "interface", volume = 0.35, pitch = 0.03, range = 0, parts = { { 0.000, 0.150 }, { 0.650, 0.150 }, { 1.300, 0.150 } } },
	ui_hover = { file = "interface", volume = 0.15, pitch = 0.03, range = 0, parts = { { 1.950, 0.100 }, { 2.550, 0.100 } } },
	ui_open = { file = "interface", volume = 0.35, pitch = 0.02, range = 0, parts = { { 3.150, 0.800 } } },
	ui_close = { file = "interface", volume = 0.3, pitch = 0.02, range = 0, parts = { { 4.450, 0.500 } } },
	ui_tab = { file = "interface", volume = 0.3, pitch = 0.04, range = 0, parts = { { 5.450, 0.400 }, { 6.350, 0.400 } } },
	ui_denied = { file = "interface", volume = 0.35, pitch = 0, range = 0, parts = { { 7.250, 0.400 } } },
	reroll = { file = "interface", volume = 0.4, pitch = 0.05, range = 0, parts = { { 8.150, 0.500 }, { 9.150, 0.500 }, { 10.150, 0.500 } } },
	reveal_common = { file = "interface", volume = 0.35, pitch = 0, range = 0, parts = { { 11.150, 0.800 } } },
	reveal_rare = { file = "interface", volume = 0.45, pitch = 0, range = 0, parts = { { 12.450, 1.500 } } },
	reveal_epic = { file = "interface", volume = 0.5, pitch = 0, range = 0, parts = { { 14.450, 2.000 } } },
	reveal_legendary = { file = "interface", volume = 0.55, pitch = 0, range = 0, parts = { { 16.950, 2.500 } } },
	reveal_mythic = { file = "interface", volume = 0.6, pitch = 0, range = 0, parts = { { 19.950, 3.500 } } },
	code_redeem = { file = "interface", volume = 0.45, pitch = 0, range = 0, parts = { { 23.950, 1.500 } } },
	magic_door_open = { file = "world", volume = 0.5, pitch = 0.04, range = 60, parts = { { 0.000, 1.200 } } },
	magic_door_close = { file = "world", volume = 0.5, pitch = 0.04, range = 60, parts = { { 1.700, 0.900 } } },
	clock_bell = { file = "world", volume = 0.6, pitch = 0, range = 500, parts = { { 3.100, 5.000 } } },
	charge_loop = { file = "charge_loop", volume = 0.3, pitch = 0, range = 60, loop = true },
	moonpool_loop = { file = "moonpool_loop", volume = 0.4, pitch = 0, range = 80, loop = true },
	underwater_loop = { file = "underwater_loop", volume = 0.4, pitch = 0, range = 80, loop = true },
	deadwood_loop = { file = "deadwood_loop", volume = 0.45, pitch = 0, range = 150, loop = true },
	shore_loop = { file = "shore_loop", volume = 0.45, pitch = 0, range = 150, loop = true },
}

local function hostFor(where)
	if typeof(where) == "Vector3" then
		local a = Instance.new("Attachment")
		a.WorldPosition = where
		a.Parent = workspace.Terrain
		Debris:AddItem(a, 8)
		return a
	end
	return where or SoundService
end

local function make(def, where, opts)
	local id = Sounds.ASSET_IDS[def.file]
	if not id or id == 0 then return nil end
	local s = Instance.new("Sound")
	s.Name = "MW_" .. def.file
	s.SoundId = "rbxassetid://" .. tostring(id)
	s.Volume = def.volume * (opts.volume or 1)
	s.PlaybackSpeed = (opts.pitch or 1) * (1 + (math.random() * 2 - 1) * (def.pitch or 0))
	s.RollOffMode = Enum.RollOffMode.InverseTapered
	s.RollOffMinDistance = 8
	s.RollOffMaxDistance = def.range > 0 and def.range or 90
	if opts.group then s.SoundGroup = opts.group end
	s.Parent = hostFor(where)
	return s
end

-- One-shot. `where` is a part/attachment, a Vector3, or nil for 2D. opts: volume, pitch (multipliers), group.
function Sounds.play(name, where, opts)
	local def = Sounds.LIST[name]
	if not def or not def.parts then return nil end
	opts = opts or {}
	local s = make(def, where, opts)
	if not s then return nil end
	local part = def.parts[math.random(#def.parts)]
	local start, len = part[1], part[2]
	-- play only this sound's stretch of the sheet
	local precise = pcall(function()
		s.PlaybackRegionsEnabled = true
		s.PlaybackRegion = NumberRange.new(start, start + len)
	end)
	s.TimePosition = start
	s:Play()
	local life = len / s.PlaybackSpeed
	if not precise then
		task.delay(life, function() if s.Parent then s:Stop() end end)
	end
	Debris:AddItem(s, life + 1)
	return s
end

-- Looping sound (charge hum, zone ambience). Returns the Sound so the caller can fade or stop it.
function Sounds.loop(name, where, opts)
	local def = Sounds.LIST[name]
	if not def or not def.loop then return nil end
	local s = make(def, where, opts or {})
	if not s then return nil end
	s.Looped = true
	s:Play()
	return s
end

-- The flavour layer for an affinity, played on top of the cast.
function Sounds.affinity(affinityName, where, opts)
	local key = Sounds.AFFINITY[affinityName or ""]
	return key and Sounds.play(key, where, opts) or nil
end

-- Call once on each client so the files are loaded before the first spell.
function Sounds.preload()
	local list = {}
	for _, id in pairs(Sounds.ASSET_IDS) do
		if id ~= 0 then
			local s = Instance.new("Sound")
			s.SoundId = "rbxassetid://" .. tostring(id)
			table.insert(list, s)
		end
	end
	if #list > 0 then
		task.spawn(function() pcall(ContentProvider.PreloadAsync, ContentProvider, list) end)
	end
end

return Sounds
